import { ECharacteristic } from '../../enums';
import { ISkill } from '../../interfaces';

export const defaultSkills: ISkill[] = [{
    characteristic: ECharacteristic.brawn,
    level: 0,
    max: 100,
    min: 0,
    name: 'athletics',
},
{
    characteristic: ECharacteristic.brawn,
    level: 0,
    max: 100,
    min: 0,
    name: 'resilience',
},
{
    characteristic: ECharacteristic.presence,
    level: 0,
    max: 100,
    min: 0,
    name: 'charm',
},
{
    characteristic: ECharacteristic.willpower,
    level: 0,
    max: 100,
    min: 0,
    name: 'coercion',
},
{
    characteristic: ECharacteristic.presence,
    level: 0,
    max: 100,
    min: 0,
    name: 'cool',
},
{
    characteristic: ECharacteristic.agility,
    level: 0,
    max: 100,
    min: 0,
    name: 'coordination',
},
{
    characteristic: ECharacteristic.cunning,
    level: 0,
    max: 100,
    min: 0,
    name: 'deception',
},
{
    characteristic: ECharacteristic.intellect,
    level: 0,
    max: 100,
    min: 0,
    name: 'knowledge',
},
{
    characteristic: ECharacteristic.cunning,
    level: 0,
    max: 100,
    min: 0,
    name: 'perception',
},
{
    characteristic: ECharacteristic.intellect,
    level: 0,
    max: 100,
    min: 0,
    name: 'medicine',
},
{
    characteristic: ECharacteristic.agility,
    level: 0,
    max: 100,
    min: 0,
    name: 'stealth',
},
{
    characteristic: ECharacteristic.cunning,
    level: 0,
    max: 100,
    min: 0,
    name: 'survival',
},
{
    characteristic: ECharacteristic.cunning,
    level: 0,
    max: 100,
    min: 0,
    name: 'skulduggery',
},
{
    characteristic: ECharacteristic.cunning,
    level: 0,
    max: 100,
    min: 0,
    name: 'streetwise',
},
{
    characteristic: ECharacteristic.brawn,
    level: 0,
    max: 100,
    min: 0,
    name: 'brawl',
},
{
    characteristic: ECharacteristic.agility,
    level: 0,
    max: 100,
    min: 0,
    name: 'gunnery',
},
{
    characteristic: ECharacteristic.brawn,
    level: 0,
    max: 100,
    min: 0,
    name: 'melee',
},
{
    characteristic: ECharacteristic.agility,
    level: 0,
    max: 100,
    min: 0,
    name: 'light ranged',
},
{
    characteristic: ECharacteristic.agility,
    level: 0,
    max: 100,
    min: 0,
    name: 'heavy ranged',
},
{
    characteristic: ECharacteristic.presence,
    level: 0,
    max: 100,
    min: 0,
    name: 'persuasion',
},
{
    characteristic: ECharacteristic.presence,
    level: 0,
    max: 100,
    min: 0,
    name: 'leadership',
},
{
    characteristic: ECharacteristic.presence,
    level: 0,
    max: 100,
    min: 0,
    name: 'negociation',
},
{
    characteristic: ECharacteristic.willpower,
    level: 0,
    max: 100,
    min: 0,
    name: 'discipline',
},
{
    characteristic: ECharacteristic.willpower,
    level: 0,
    max: 100,
    min: 0,
    name: 'vigilance',
}
];

